{{- $site := (include "skupper-rabbitmq-cluster.name" .)}}
{{- $slaveCount := .Values.replicaCount -}}
{{- range (untilStep 0 (int $slaveCount) 1)}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    skupper.io/address: skupper-rabbit-{{ $site}}-{{ . }}
    skupper.io/port: "5671,5672,25672,15672,4369,15671"
    skupper.io/proxy: "tcp"
    skupper.io/target: "skupperrabbit-{{ $site}}-{{ . }}"
  labels:
    app: skupper-rabbit-{{ $site}}-{{ . }}
  name: skupperrabbit-{{ $site}}-{{ . }}
spec:
  publishNotReadyAddresses: true
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: dist
    port: 25672
    protocol: TCP
    targetPort: 25672
  - name: http-stats
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: https-stats
    port: 15671
    protocol: TCP
    targetPort: 15671
  selector:
    app: skupper-rabbit-{{ $site}}-{{ . }}
  sessionAffinity: None
  type: ClusterIP
{{- end -}}