{{- $site := (include "skupper-rabbitmq-cluster.name" .) -}}
{{- $slaveCount := .Values.replicaCount -}}
{{- range (untilStep 0 (int $slaveCount) 1) -}}
{{- $nodesleeptime := mul . 60 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skupper-rabbit-{{ $site}}-{{ . }}
    cluster: skupperrabbitmq
  name: skupper-rabbit-{{ $site}}-{{ . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: skupper-rabbit-{{ $site }}-{{ . }}
      cluster: skupperrabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: skupper-rabbit-{{ $site }}-{{ . }}
        cluster: skupperrabbitmq
    spec:
      initContainers:
      - name: waitforsvc
        image: alpine
        command: ['sh', '-c', "sleep {{ $nodesleeptime }};until nslookup skupper-rabbit-{{ $site }}-{{ . }}.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for rabbitmq dns; sleep 2; done"]
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
      containers:
      - env:
          - name: BITNAMI_DEBUG
            value: 'true'
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: K8S_SERVICE_NAME
            value: skupper-rabbit-{{ $site }}-{{ . }}
          - name: K8S_ADDRESS_TYPE
            value: hostname
          - name: RABBITMQ_NODE_NAME
            value: "rabbit@$(K8S_SERVICE_NAME)"
          - name: RABBITMQ_FORCE_BOOT
            value: 'no'
          - name: K8S_HOSTNAME_SUFFIX
            value: .$(K8S_SERVICE_NAME)
          - name: RABBITMQ_MNESIA_DIR
            value: /bitnami/rabbitmq/mnesia/$(RABBITMQ_NODE_NAME)
          - name: RABBITMQ_LDAP_ENABLE
            value: 'no'
          - name: RABBITMQ_LOGS
            value: '-'
          - name: RABBITMQ_ULIMIT_NOFILES
            value: '65536'
          - name: RABBITMQ_USE_LONGNAME
            value: 'false'
          - name: RABBITMQ_ERL_COOKIE
            value: testing
          - name: RABBITMQ_LOAD_DEFINITIONS
            value: 'no'
          - name: RABBITMQ_SECURE_PASSWORD
            value: 'yes'
          - name: RABBITMQ_USERNAME
            value: anz
          - name: RABBITMQ_PASSWORD
            value: anz
          - name: RABBITMQ_ADVANCED_CONFIG_FILE
            value: /bitnami/rabbitmq/conf/advanced.config
          - name: RABBITMQ_PLUGINS
            value: >-
              rabbitmq_management
        image: bitnami/rabbitmq:3.9.13-debian-10-r31
        imagePullPolicy: Always
        name: skupper-rabbit-{{ $site }}-{{ . }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - '-c'
                - >
                  echo "sleep 120; rabbitmqctl --erlang-cookie ${RABBITMQ_ERL_COOKIE} set_policy ha-all \".*\" '{\"ha-mode\":\"all\"}'" > /tmp/script.sh
                  && chmod 777 /tmp/script.sh && /tmp/script.sh &
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi        
        readinessProbe:
          exec:
            command:
              - rabbitmqctl
              - status
          failureThreshold: 10
          initialDelaySeconds: 50
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
              - rabbitmqctl
              - status
          failureThreshold: 10
          initialDelaySeconds: 50
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 25672
            name: dist
            protocol: TCP
          - containerPort: 15672
            name: stats
            protocol: TCP
          - containerPort: 4369
            name: epmd
            protocol: TCP
          - containerPort: 5671
            name: amqps
            protocol: TCP
          - containerPort: 15671
            name: https
            protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: configuration
            mountPath: /bitnami/rabbitmq/conf/rabbitmq.conf
            subPath: rabbitmq.conf
          - name: configuration
            mountPath: /bitnami/rabbitmq/conf/advanced.config
            subPath: advanced.config
          - mountPath: /bitnami/rabbitmq/mnesia
            name: data
          - mountPath: /etc/rabbitmq/ssl
            name: rmq-ssl
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: configuration
          configMap:
            name: skupper-rabbitmq-config
            defaultMode: 420
          name: configuration
        - name: data
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: skupper-rabbit-{{ $site}}-{{ . }}
        - name: rmq-ssl
          secret:
            secretName: skupper-rabbitmq-certs
{{- end -}}