apiVersion: v1
kind: Service
metadata:
  annotations:
    skupper.io/address: skupperrabbitmq
    skupper.io/port: "5671,5672,25672,15672,4369,15671"
    skupper.io/proxy: "tcp"
  labels:
    app: skupperrabbitmq
    cluster: skupperrabbitmq
  name: ocskupperrabbitmq
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: dist
    port: 25672
    protocol: TCP
    targetPort: 25672
  - name: http-stats
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: https-stats
    port: 15671
    protocol: TCP
    targetPort: 15671
  selector:
    cluster: skupperrabbitmq
  sessionAffinity: None
  type: ClusterIP